#ifndef MAIN_SOURCE
  #define EXTERN extern
#else
  #define EXTERN
#endif

extern void figlet(User,char *,int);
EXTERN int com_num;
EXTERN char *com_style[]
#ifdef MAIN_SOURCE
	={
		"Messages","Rooms","Speech","General","FunNGames",
		"Server",  "Misc.","Admin",  "*"
	}
#endif
;

enum comstyle
{
	MESGS,	ROOMS,	SPEECH,  GENERAL,  GAMES,  SERVER,  MISCCM,
	STAFF
};

EXTERN struct
{
	char name[21];
	int lev,type;
	user_function funct;
	int args;
} command[]
#ifdef MAIN_SOURCE
  ={
	{ "quit",	NEWBIE,	GENERAL,	quit_user,	0 },
	{ "look",	NEWBIE,	ROOMS,		look,		0 },
	{ "say",	NEWBIE,	SPEECH,		say,		0 },
	{ "shout",	USER,	SPEECH,		shout,		0 },
	{ "tell",	USER,	SPEECH,		multi_message,	1 },
	{ "emote",	USER,	SPEECH,		emote,  	0 },
	{ "semote",	USER,	SPEECH,		shout_emote,	0 },
	{ "pemote",	USER,	SPEECH,		multi_message,  2 },
	{ "echo",	USER,	SPEECH,		send_echo,      0 },
	{ "go",		USER,	ROOMS,		go,		0 },
	{ "ignore",	USER,	GENERAL,	ignore,		0 },
	{ "desc",	USER,	GENERAL,	set_desc,	0 },
	{ "unlock",	USER,	ROOMS,		set_room_access,0 },
	{ "lock",	USER,	ROOMS,		set_room_access,1 },
	{ "knock",	USER,	ROOMS,		knock,		0 },
	{ "invite",	USER,	ROOMS,		invite,		0 },
	{ "to",		USER,	SPEECH,		to_user,	0 },
	{ "move",	WIZ,	ROOMS,		staff_move,	0 },
	{ "who",	NEWBIE,	GENERAL,	who,		0 },
	{ "set",	NEWBIE,	GENERAL,	setmeup,	0 },
	{ "help",	NEWBIE,	GENERAL,	help,		0 },
	{ "shutdown",	GOD,	STAFF,		shutdown_com,	0 },
	{ "news",	USER,	MESGS,		page_file,	1 },
	{ "read",	USER,	MESGS,		read_board,	0 },
	{ "write",	USER,	MESGS,		write_board,	0 },
	{ "wipe",	USER,	MESGS,		delete_messages,1 },
	{ "review",	USER,	ROOMS,		review_buffer,	0 },
	{ "stats",	USER,	GENERAL,	stats,		0 },
	{ "rmail",	USER,	MESGS,		rmail,		0 },
	{ "version",	NEWBIE, GENERAL,	what_version,	0 },
	{ "rmkick",	SUPER,	ROOMS,		kick_out,	0 },
	{ "smail",	USER,	MESGS,		smail,		0 },
	{ "dmail",	USER,	MESGS,		delete_messages,2 },
	{ "from",	USER,	MESGS,		view_from,	2 },
	{ "entpro",	NEWBIE, MESGS,		enter_profile,	0 },
	{ "examine",	USER,	GENERAL,	examine,	0 },
	{ "passwd",	USER,	GENERAL,	change_pass,	0 },
	{ "kill",	ADMIN,	STAFF,		kill_user,	1 },
	{ "promote",	ADMIN,	STAFF,		promote,	1 },
	{ "demote",	ADMIN,	STAFF,		demote,		1 },
	{ "list",	SUPER,	GAMES,		list_games,	0 },
	{ "ban",	WIZ,	STAFF,		ban,		0 },
	{ "unban",	WIZ,	STAFF,		unban,		0 },
	{ "vis",	SUPER,	MISCCM,		visibility,	0 },
	{ "invis",	SUPER,	MISCCM,		visibility,	1 },
	{ "sites",	WIZ,	STAFF,		site,		0 },
	{ "wake",	POWER,	GENERAL,	wake,		0 },
	{ "wiztell",	WIZ,	SPEECH,		wiztell,	0 },
	{ "muzzle",	WIZ,	STAFF,		muzzle,		0 },
	{ "unmuzzle",	WIZ,	STAFF,		unmuzzle,	0 },
	{ "map",	USER,	ROOMS,		map,		0 },
	{ "minlogin",	ADMIN,	STAFF,		minlogin,	0 },
	{ "system",	ADMIN,	SERVER,		system_details,	0 },
	{ "clearline",	ADMIN,	STAFF,		clearline,	0 },
	{ "home",	USER,	ROOMS,		goto_myroom,	0 },
	{ "wemote",	WIZ,	SPEECH,		wizemote,	0 },
	{ "view",	WIZ,	STAFF,		view_logs,	0 },
	{ "cbuff",	USER,	ROOMS,		clear_buffers,	0 },
	{ "clone",	WIZ,	MISCCM,		create_clone,	0 },
	{ "destroy",	WIZ,	MISCCM,		destroy_clone,	0 },
	{ "myclones",	WIZ,	MISCCM,		myclones,	0 },
	{ "switch",	WIZ,	MISCCM,		clone_switch,	0 },
	{ "cexec",	WIZ,	MISCCM,		clone_exec,	0 },
	{ "chear",	WIZ,	MISCCM,		clone_hear,	0 },
	{ "uninvite",	USER,	ROOMS,		uninvite,	0 },
	{ "swban",	GOD,	STAFF,		swban,		0 },
	{ "afk",	USER,	GENERAL,	afk,		0 },
	{ "cls",	NEWBIE,	GENERAL,	cls,		0 },
	{ "nobuff",	POWER,	ROOMS,		nobuff,		0 },
	{ "suicide",	NEWBIE,	MISCCM,		suicide,	0 },
	{ "nuke",	ADMIN,	STAFF,		delete_user,	0 },
	{ "reboot",	ADMIN,	STAFF,		reboot_com,	0 },
	{ "join",	USER,	ROOMS,		join,		0 },
	{ "recount",	GOD,	MESGS,		check_messages, 2 },
	{ "getname",	ADMIN,	SERVER,		get_real_name,	0 },
	{ "bank",	USER,	MISCCM,		bank,		0 }, 
	{ "icqpage",	SUPER,	SERVER,		icqpage,	0 },
	{ "scut",	USER,	GENERAL,	shortcuts,	0 },
	{ "tpromo",	WIZ,	STAFF,		promote,	2 },
	{ "boot",	WIZ,	STAFF,		kill_user,	2 },
	{ "tdemote",	WIZ,	STAFF,		demote,		2 },
	{ "randsoc",	SUPER,	GAMES,		random_social,	0 },
	{ "toss",	SUPER,	GAMES,		flip_coin,	0 },
	{ "arrest",	WIZ,	STAFF,		arrest,		0 },
	{ "unarrest",	WIZ,	STAFF,		unarrest,	0 },
	{ "silence",	ADMIN,	STAFF,		silence,	0 },
	{ "unsilence",	ADMIN,	STAFF,		unsilence,	0 },
	{ "bcast",	WIZ,	SPEECH,		broad_cast,	0 },
	{ "record",	WIZ,	MESGS,		view_record,	0 },
	{ "finger",	ADMIN,	SERVER,		uni_inger,	0 },
	{ "whois",	ADMIN,	SERVER,		uni_ois,	0 },
	{ "nslookup",	ADMIN,	SERVER,		ns_lookup,	0 },
	{ "gag",	WIZ,	STAFF,		gag,		0 },
	{ "change",	OWNER,	STAFF,		change_system,	0 },
	{ "sreboot",	ADMIN,	STAFF,		sreboot_com,	0 },
	{ "figlet",	SUPER,	GAMES,		figlet,		0 },
	{ "fakelog",	WIZ,	STAFF,		fake_logoff,	0 },
	{ "shackle",	WIZ,	STAFF,		shackle,	1 },
	{ "unshackle",	WIZ,	STAFF,		shackle,	2 },
	{ "mkvis",	WIZ,	STAFF,		make_visible,	0 },
	{ "mkinvis",	WIZ,	STAFF,		make_invis,	0 },
	{ "addhist",	WIZ,	MESGS,		add_user_hist,	0 },
	{ "samesite",	WIZ,	STAFF,		samesite,	0 },
	{ "rename",	ADMIN,	STAFF,		change_name,	0 },
	{ "saveusers",	WIZ,	MISCCM,		save_users,	0 },
	{ "resign",	WIZ,	STAFF,		resign_staff,	0 },
	{ "disable",	GOD,	STAFF,		disable_command,0 },
	{ "deny",	ADMIN,	STAFF,		deny_command,	0 },
	{ "allow",	ADMIN,	STAFF,		allow_command,	0 },
	{ "strules",	WIZ,	STAFF,		page_file,	2 },
	{ "topic",	USER,	ROOMS,		set_topic,	0 },
	{ "think",	USER,	SPEECH,		think,		0 },
	{ "sing",	USER,	SPEECH,		sing,		0 },
	{ "show",	POWER,	MISCCM,		show,		0 },
	{ "mutter",	SUPER,	SPEECH,		mutter,		0 },
	{ "pecho",	POWER,	SPEECH,		private_echo,	0 },
	{ "pthink",	SUPER,	SPEECH,		multi_message,	3 },
	{ "psing",	SUPER,	SPEECH,		multi_message,	4 },
	{ "beep",	USER,	SPEECH,		send_beep,	0 },
	{ "shecho",	SUPER,	SPEECH,		shout_echo,	0 },
	{ "sthink",	SUPER,	SPEECH,		shout_think,	0 },
	{ "ssing",	SUPER,	SPEECH,		shout_sing,	0 },
	{ "welcome",	SUPER,	SPEECH,		welcome_user,	0 },
	{ "yell",	POWER,	SPEECH,		yell,		0 },
	{ "ftell",	USER,	SPEECH,		friend_tell,	0 },
	{ "femote",	USER,	SPEECH,		friend_emote,	0 },
	{ "tictac",	USER,	GAMES,		tictac,		0 },
	{ "toemote",	USER,	SPEECH,		to_emote,	0 },
	{ "connect4",	USER,	GAMES,		connect_four,	0 },
	{ "start",	SUPER,	GAMES,		start_poker,	0 },
	{ "pojoin",	SUPER,	GAMES,		join_poker,	0 },
	{ "leave",	SUPER,	GAMES,		leave_poker,	0 },
	{ "listbans",	WIZ,	STAFF,		listbans,	0 },
	{ "deal",	SUPER,	GAMES,		deal_poker,	0 },
	{ "bet",	SUPER,	GAMES,		bet_poker,	0 },
	{ "raise",	SUPER,	GAMES,		raise_poker,	0 },
	{ "see",	SUPER,	GAMES,		see_poker,	0 },
	{ "fold",	SUPER,	GAMES,		fold_poker,	0 },
	{ "check",	SUPER,	GAMES,		check_poker,	0 },
	{ "discard",	SUPER,	GAMES,		discard_poker,	0 },
	{ "hand",	SUPER,	GAMES,		hand_poker,	0 },
	{ "games",	SUPER,	GAMES,		show_players,	0 },
	{ "hangman",	USER,	GAMES,		hangman,	0 },
	{ "slots",	SUPER,	GAMES,		slots,		0 },
	{ "fight",	USER,	GAMES,		fight_another,	0 },
	{ "monitor",	POWER,	MISCCM,		toggle_monitor, 0 },
	{ "hide",	POWER,	MISCCM,		visibility,	2 },
	{ "listen",	USER,	GENERAL,	listen_up,	0 },
	{ "ignall",	USER,	GENERAL,	toggle_ignall,	0 },
	{ "helpme",	NEWBIE,	MISCCM,		helpme,		0 },
	{ "nofollow",	USER,	GENERAL,	nofollow,	0 },
	{ "nofight",	USER,	GENERAL,	nofight,	0 },
	{ "friend",	USER,	MISCCM,		friends,	0 },
	{ "beg",	NEWBIE,	MISCCM,		beg_wizzes,	0 },
	{ "rules",	NEWBIE,	GENERAL,	page_file,	3 },
	{ "staff",	NEWBIE,	GENERAL,	staff_list,	0 },
	{ "newbie",	NEWBIE,	MISCCM,		page_file,	5 },
	{ "rlook",	POWER,	ROOMS,		room_look,	0 },
	{ "force",	ADMIN,	STAFF,		force,		0 },
	{ "warn",	WIZ,	STAFF,		warn_user,	0 },
	{ "greet",	USER,	GAMES,		greet,		0 },
	{ "earn",	USER,	MISCCM,		earn_money,	0 },
	{ "follow",	SUPER,	MISCCM,		follow,		0 },
	{ "last",	USER,	GENERAL,	last,		0 },
	{ "fwho",	USER,	GENERAL,	friend_who,	0 },
	{ "money",	USER,	MISCCM,		show_money,	0 },
	{ "text",	USER,	MESGS,		text_read,	0 },
	{ "with",	SUPER,	ROOMS,		with_user,	0 },
	{ "piclist",	USER,	MISCCM,		picture_list,	0 },
	{ "vpic",	USER,	MISCCM,		view_picture,	0 },
	{ "roompic",	POWER,	MISCCM,		room_picture,	0 },
	{ "ptell",	USER,	MISCCM,		picture_tell,	0 },
	{ "socials",	USER,	GAMES,		socials,	0 },
	{ "wizwho",	NEWBIE,	GENERAL,	wiz_who,	0 },
	{ "trivia",	USER,	GAMES,		trivia,		0 },
	{ "wait",	SUPER,	MISCCM,		waitfor_user,	0 },
	{ "riddle",	USER,	GAMES,		riddle,		0 },
	{ "finduser",	SUPER,	MISCCM,		find_user,	0 },
	{ "vote",	USER,	GAMES,		vote,		0 },
	{ "addnews",	ADMIN,	MESGS,		add_news,	0 },
	{ "entroom",	WIZ,	MESGS,		room_desc,	0 },
	{ "suggest",	USER,	MESGS,		suggestions,	0 },
	{ "bug",	USER,	MESGS,		bugs,		0 },
	{ "mail",	USER,	MESGS,		mail_menu,	0 },
	{ "eightball",	SUPER,	GAMES,		eight_ball,	0 },
	{ "bfrom",	USER,	MESGS,		view_from,	1 },
	{ "fsmail",	USER,	SERVER,		forward_smail,	0 },
	{ "rsent",	USER,	MESGS,		read_sent,	0 },
	{ "dsent",	USER,	MESGS,		delete_messages,3 },
	{ "talker",	USER,	GENERAL,	talkers,	0 },
	{ "store",	USER,	MISCCM,		store,		0 },
#ifdef HAVE_BSHIP
	{ "bship",	POWER,	GAMES,		battle_ship,	0 },
#endif
	{ "execall",	SUPER,	GAMES,		exec_all,	0 },
	{ "atmos",	USER,	ROOMS,		edit_atmos,	0 },
	{ "hatcolour",	USER,	GAMES,		hat_colour,	0 },
	{ "phone",	USER,	GAMES,		phone,		0 },
	{ "rmadmin",	OWNER,	ROOMS,		room_admin,	0 },
	{ "answer",	USER,	GAMES,		answer_call,	0 },
	{ "hangup",	USER,	GAMES,		hangup_phone,	0 },
	{ "channel",	USER,	SPEECH,		channel_say,	0 },
	{ "chemote",	USER,	SPEECH,		channel_emote,	0 },
	{ "delold",	ADMIN,	STAFF,		delete_old,	0 },
	{ "speech",	SUPER,	GAMES,		set_speech,	0 },
	{ "aliases",	USER,	GENERAL,	aliases,	0 },
	{ "edit",	USER,	MESGS,		room_desc,	0 },
	{ "mkuser",	ADMIN,	STAFF,		make_newuser,	0 },
	{ "load",	GOD,	STAFF,		load_tvars,	0 },
	{ "enemy",	USER,	MISCCM,		enemies,	0 },
	{ "netsex",	USER,	GAMES,		net_sex,	0 },
	{ "marry",	USER,	MISCCM,		net_marry,	0 },
	{ "divorce",	USER,	MISCCM,		net_divorce,	0 },
	{ "gstat",	USER,	GAMES,		game_stats,	0 },
	{ "memcnt",	ADMIN,	SERVER,		memory_count,	0 },
	{ "backup",	ADMIN,	SERVER,		force_backup,	0 },
	{ "levels",	NEWBIE,	GENERAL,	page_file,	6 },
	{ "macros",	SUPER,	MISCCM,		macros,		0 },
	{ "topen",	POWER,	SERVER,		telnet_com,	0 },
	{ "tsay",	POWER,	SERVER,		telnet_say,	0 },
	{ "tclose",	POWER,	SERVER,		telnet_close,	0 },
	{ "tphone",	POWER,	SERVER,		telnet_phone,	0 },
	{ "tlist",	SUPER,	SERVER,		telnet_list,	0 },
	{ "lynx",	POWER,	SERVER,		goto_webpage,	0 },
	{ "session",	USER,	GAMES,		check_session,	0 },
	{ "comment",	USER,	GAMES,		comment,	0 },
	{ "rmname",	USER,	ROOMS,		set_roomname,	0 },
	{ "give",	WIZ,	MISCCM,		give_stuff,	0 },
	{ "capture",	USER,	GENERAL,	capture,	0 },
	{ "protect",	ADMIN,	STAFF,		protect,	0 },
	{ "alarm",	SUPER,	GAMES,		user_alarm,	0 },
	{ "guess",	USER,	GAMES,		guess_it,	0 },
	{ "time",	USER,	GENERAL,	what_time,	0 },
	{ "redotime",	ADMIN,	STAFF,		redo_time,	0 },
	{ "shoutban",	GOD,	STAFF,		toggle_shoutban,0 },
	{ "ccopy",	SUPER,	MESGS,		set_ccopy,	0 },
	{ "screen",	GOD,	STAFF,		screen_site,	0 },
	{ "splitscr",	USER,	GENERAL,	set_splitscr,	0 },
	{ "pet",	USER,	GAMES,		pet_stuff,	0 },
	{ "rroul",	USER,	GAMES,		rroulette,	0 },
	{ "drink",	USER,	GAMES,		drink,		0 },
	{ "nbomb",	USER,	GAMES,		nuclear_bomb,	0 },
	{ "sfrom",	USER,	MESGS,		view_from,	3 },
	{ "bjack",	SUPER,	GAMES,		black_jack,	0 },
	{ "puzzle",	SUPER,	GAMES,		play_puzzle,	0 }, 
	{ "ping",       SUPER,  GAMES,		ping_user,	0 }, 
	{ "ltell",	ADMIN,	STAFF,		line_tell,	0 },
	{ "wiznote",	WIZ,	MESGS,		wiznote,	0 },
	{ "cloak",	WIZ,	STAFF,		cloak_level,	0 },
	{ "email",	POWER,  MESGS,		email_user,	0 },
	{ "make",	OWNER,	STAFF,		mymake,		0 },
	{ "reset",	GOD,	STAFF,		reset_user,	0 },
	{ "chess",	POWER,	GAMES,		chess_com,	0 },
	{ "cmove",	POWER,	GAMES,		move_pieces,	0 },
	{ "craps",	USER,	GAMES,		play_craps,	0 },
	{ "hidice",	SUPER,	GAMES,		PlayHighDice,	0 },
	{ "triples",	SUPER,	GAMES,		play_triples,	0 },
	{ "seven",	SUPER,	GAMES,		play_seven,	0 },
	{ "lottery",	USER,	GAMES,		lottery,	0 },
	{ "rmkey",	USER,	ROOMS,		room_key,	0 },
	{ "steal",	SUPER,	MISCCM,		steal_stuff,	0 },
	{ "baninfo",	ADMIN,	STAFF,		ban_info,	0 },
	{ "checkers",	SUPER,  GAMES,		checkers_com,	0 },
	{ "chmove",	SUPER,	GAMES,		move_checkers,  0 },
	/* !!Stopping clause is below, don't remove the line below!! */
	{ "*",		-1,	-1,		NULL,		-1 }
	}
#endif
;
#undef EXTERN
